[[Popt]]
arch = "aarch64"
git-tree-sha1 = "0e291f77d9c9e334d1037ffab7c19ec7129817f3"
os = "macos"

    [[Popt.download]]
    sha256 = "128607160e6c5c33498569363a2bad27cec3eb3ba707f0e95d2e821f26aaaa5f"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.aarch64-apple-darwin.tar.gz"
[[Popt]]
arch = "aarch64"
git-tree-sha1 = "763bfa8258c44b16252867277357eeb14c5ab54b"
libc = "glibc"
os = "linux"

    [[Popt.download]]
    sha256 = "48a1b030cb1d92cfbe2d7526ff2905a8ac75ccc61cf0f95769000135121d4a1e"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.aarch64-linux-gnu.tar.gz"
[[Popt]]
arch = "aarch64"
git-tree-sha1 = "b35f3898a594be3b0ec1fc2837f949bc13efb486"
libc = "musl"
os = "linux"

    [[Popt.download]]
    sha256 = "7bccc83eefb1f7bfe2d58addfef3cc729491afcc6fa223dbc068dd2de81f00ea"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.aarch64-linux-musl.tar.gz"
[[Popt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a56fbcb9684d430d1bbcf5ef37f469f840b3e3a5"
libc = "glibc"
os = "linux"

    [[Popt.download]]
    sha256 = "5c1f1765d41ffc71753b3b23d897294cee2e45416a2d09d00ea239f56ed75517"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.armv6l-linux-gnueabihf.tar.gz"
[[Popt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4f9aa4a69b605a73db8b015905f38b05033feb7b"
libc = "musl"
os = "linux"

    [[Popt.download]]
    sha256 = "2aad8cafaff229dc0365fe78ed887d71d94a2aa96dd0e0700d1bc3184d92a6f7"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.armv6l-linux-musleabihf.tar.gz"
[[Popt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aa449c278e3c899208f6398bb5664a93805d0dc1"
libc = "glibc"
os = "linux"

    [[Popt.download]]
    sha256 = "4ca7a0a18e70372de7ea7a60a4ee021932e492b8bc17a5245916f4460cec5cce"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.armv7l-linux-gnueabihf.tar.gz"
[[Popt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ce809c0bbc4a6d07ebca253e4d4cb8d980c63db9"
libc = "musl"
os = "linux"

    [[Popt.download]]
    sha256 = "5414691eba09f5a71d079340beac2e4f06a72f7c365a87b6dafe80e2af61750d"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.armv7l-linux-musleabihf.tar.gz"
[[Popt]]
arch = "i686"
git-tree-sha1 = "a06776759a655c685740f2f72255b220d8aa8d9d"
libc = "glibc"
os = "linux"

    [[Popt.download]]
    sha256 = "7e0eda748a2ee94cf4e9c24fa3b64a02c157d36c9d93a58ca6488002147d89f9"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.i686-linux-gnu.tar.gz"
[[Popt]]
arch = "i686"
git-tree-sha1 = "b18fd0a894c472e15e6d6fb8a66f5b38f94963e5"
libc = "musl"
os = "linux"

    [[Popt.download]]
    sha256 = "ced51d8c90540aab7b826c09960c0418ece6c1212036337629f4101a241e23e1"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.i686-linux-musl.tar.gz"
[[Popt]]
arch = "i686"
git-tree-sha1 = "2e2d14fb04572cd90788ce19ba5a1d4ba080272c"
os = "windows"

    [[Popt.download]]
    sha256 = "be0ca5c4d26d7a0debc0f613aa8df4b16a1fd6b6eb7ba14000a15d56be7bd34a"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.i686-w64-mingw32.tar.gz"
[[Popt]]
arch = "powerpc64le"
git-tree-sha1 = "20adf57b0a0ce1247b5c28e3c77572111890fc5c"
libc = "glibc"
os = "linux"

    [[Popt.download]]
    sha256 = "36d41b442894c05f7aaf15556c8f99b43db76e3f139d92b3c2af26b3175881d9"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.powerpc64le-linux-gnu.tar.gz"
[[Popt]]
arch = "x86_64"
git-tree-sha1 = "98390094b121a95fc9be6b80c689e4ed02b3e10b"
os = "macos"

    [[Popt.download]]
    sha256 = "17dfcd2c988ed6aa9a970257fb370f6f2ed3426cc9079d61217bee75e7d1e8f0"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.x86_64-apple-darwin.tar.gz"
[[Popt]]
arch = "x86_64"
git-tree-sha1 = "bca70ff465f760e4037171adb7ce6719666c1efd"
libc = "glibc"
os = "linux"

    [[Popt.download]]
    sha256 = "e762c52de1c0af462e06ccba30e888d5120d22a84cff926c8ca41d9f484dc885"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.x86_64-linux-gnu.tar.gz"
[[Popt]]
arch = "x86_64"
git-tree-sha1 = "62c0f54bcedbf3eb0bf33cdf0001aab257b022da"
libc = "musl"
os = "linux"

    [[Popt.download]]
    sha256 = "1154b67923ef743a78981afe36f3767fbe6223acdb4179e23b81efd4cbc48bf2"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.x86_64-linux-musl.tar.gz"
[[Popt]]
arch = "x86_64"
git-tree-sha1 = "974498f88d6668f0ca10d81e2f5765112fa89790"
os = "freebsd"

    [[Popt.download]]
    sha256 = "a7d6dc5b2760a2ae6d9f95b46b5e3f06f18f4430d5016e8dcd869f3588ee3af3"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.x86_64-unknown-freebsd.tar.gz"
[[Popt]]
arch = "x86_64"
git-tree-sha1 = "a93840dad695cec5271774bc6d69ec0de5a61b34"
os = "windows"

    [[Popt.download]]
    sha256 = "165a578d991df5ccf9cb99c103af06121d7b651d6db372492e4bea20c6f62176"
    url = "https://github.com/JuliaBinaryWrappers/Popt_jll.jl/releases/download/Popt-v1.19.0+0/Popt.v1.19.0.x86_64-w64-mingw32.tar.gz"
